language: java
 
sudo: required

jdk:
   - openjdk8

install: true

script:
  - java -version
  - ./fpinkotlin-parent/gradlew assemble

notifications:
  email:
    recipients:
      - build@volga.fr
    on_success: always # default: change [always|never|change]
    on_failure: always # default: always [always|never|change]
